#VWG->Xaero Audit-only v2 Repair
#Low-overhead defaults; tweak carefully.
#Mon Jul 27 18:20:29 CDT 2026
enabled=true
interval_ticks=40
max_regions_per_tick=2
near_radius=2
repair_cooldown_ticks=200
time_budget_micros=1000
top_k=6
vanilla_only_fallback_upgrade_enabled=false
vanilla_only_repair_enabled=false
