#VWG->Xaero Audit-only v1
#Low-overhead defaults. Adjust carefully if server thread is sensitive.
#Mon Jul 27 18:20:29 CDT 2026
enabled=true
interval_ticks=40
loaded_ttl_ticks=1200
max_regions_per_tick=2
mca_header_refresh_ticks=200
near_radius=2
time_budget_micros=1000
top_k=6
